name: Update docs from highest assignment branch

on:
  workflow_dispatch:

jobs:
  copy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # fetch all branches

    - name: Get highest assignment branch
      id: get_branch
      run: |
        # list remote branches matching assignment-*
        branches=$(git for-each-ref --format='%(refname:short)' refs/remotes/origin/assignment-* | sed 's|origin/||')
        echo "Found branches: $branches"

        # get the highest number
        highest=$(echo "$branches" | sed 's/assignment-//' | sort -n | tail -1)
        highest_branch="assignment-$highest"
        echo "Highest assignment branch: $highest_branch"

        echo "branch=$highest_branch" >> $GITHUB_OUTPUT

    - name: Copy docs from highest assignment branch
      run: |
        # get docs from highest assignment branch into main
        git checkout ${{ steps.get_branch.outputs.branch }} -- docs

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs
        git commit -m "Update docs from ${{ steps.get_branch.outputs.branch }}" || echo "No changes to commit"
        git push origin main
