name: Update docs from highest assignment branch

on:
  push:
    branches:
      - 'assignment-*'

jobs:
  copy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get highest assignment branch
      id: get_branch
      run: |
        branches=$(git for-each-ref --format='%(refname:short)' refs/remotes/origin/assignment-* | sed 's|origin/||')
        highest=$(echo "$branches" | sed 's/assignment-//' | sort -n | tail -1)
        highest_branch="assignment-$highest"
        echo "branch=$highest_branch" >> $GITHUB_OUTPUT

    - name: Copy docs from highest assignment branch
      run: |
        git fetch origin ${{ steps.get_branch.outputs.branch }}:refs/remotes/origin/${{ steps.get_branch.outputs.branch }}
        git checkout origin/${{ steps.get_branch.outputs.branch }} -- docs

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs
        git commit -m "Update docs from ${{ steps.get_branch.outputs.branch }}" || echo "No changes to commit"
        git push origin main
